#!/bin/bash

# Skip pre-commit checks if commit author is GitHub Actions bot.
if [ "$(git config --get user.name)" == "github-actions[bot]" ]; then
    echo "🤖 GitHub Actions bot detected, skipping commitizen."
    exit 0
fi

# For all other commits: run pre-commit checks.
pnpm verify
