#!/bin/bash

# Skip pre-commit checks if commit author is GitHub Actions bot.
if git config --get user.name | grep -q "github-actions[bot]"; then
    echo "🤖 GitHub Actions bot detected, skipping verification."
    exit 0
fi

# For all other commits: run pre-commit checks.
# pnpm verify
